// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXvWxIcts2Nd8QW-prkD3rJHKxqMIyzUg',
    appId: '1:294766590074:web:fbe25231b8ef11d8afe3c3',
    messagingSenderId: '294766590074',
    projectId: 'store-connect-app',
    authDomain: 'store-connect-app.firebaseapp.com',
    storageBucket: 'store-connect-app.firebasestorage.app',
    measurementId: 'G-KYVFYLZHSQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3glXnB8XDm1IUFfKUGmaNcULnUZF_hrM',
    appId: '1:294766590074:android:82c38b9f3a34123dafe3c3',
    messagingSenderId: '294766590074',
    projectId: 'store-connect-app',
    storageBucket: 'store-connect-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaCodBjSTYs3dtw2spwo2VUmMkSzr8pTw',
    appId: '1:294766590074:ios:d63ffe7b20842043afe3c3',
    messagingSenderId: '294766590074',
    projectId: 'store-connect-app',
    storageBucket: 'store-connect-app.firebasestorage.app',
    iosBundleId: 'com.rodrigocostadev.storeconnect.storeConnect',
  );
}
